Fix CI
bitrise-io/steps-codecov pull request #10
Opened 2017-03-17 16:31 UTC by trapacska

2017-03-17 16:34 UTC, stevepeak commented
Thank you @trapacska 

Suggested reviewers: @viktorbenei and/or @birmacher Thanks

2017-03-17 16:35 UTC, trapacska commented
Sure, I'll ping @viktorbenei 🎉

2017-03-18 09:23 UTC, viktorbenei requested changes

2017-03-18 09:23 UTC, viktorbenei commented on step.yml
> -        Example: `-F unittests -J '^Project'`
revert this - see: https://github.com/bitrise-io/steps-codecov/pull/9

2017-03-18 09:24 UTC, viktorbenei commented
Otherwise 👍

2017-03-20 09:11 UTC, viktorbenei approved these changes

2017-03-20 09:23 UTC, godrei commented on bitrise.yml
> +    - script:
please do this, this way: https://github.com/bitrise-steplib/steps-xamarin-archive/blob/master/bitrise.yml#L32

2017-03-20 09:59 UTC, godrei approved these changes
👌

2017-03-20 10:04 UTC, merged